on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@da0d77ff390a13097c60f9b9eb954e503a480d97
      with:
        ftp-server: ftp://files.000webhost.com
        ftp-username: dsc-gpf
        ftp-password: dsc@-#gpf
        git-ftp-args: --insecure --remote-root public_html/
